export { default as TopHeader } from './header/TopHeader'
export { default as Menu } from './header/Menu'
export { default as Slider } from './slider/Slider'
export { default as Footer } from './footer/Footer'
export { default as CosmeticsPage } from './cosmeticsPage/CosmeticsPage'
export { default as HairPage } from './hairPage/HairPage'
export {default as SkinPage} from './skinPage/SkinPage'
export {default as WomenHealthPage} from './womenHealthPage/WomenHealthPage'
export {default as MenHealthPage} from './menHealthPage/MenHealthPage'
export {default as ChildrenHealthPage} from './childrenHealthPage/ChildHealthPage'
export {default as LatestProducts} from './latestProduct/LatestProducts'
export {default as DailyDeal} from './dailyDeal/DailyDeal'
export {default as ProductCategories} from './productCategory/ProductCategories'
export {default as ContactUs} from './contactUsPage/ContactUs'
export {default as AboutUs} from './aboutUsPage/AboutUs'
export{default as SearchPage} from './search/SearchPage'
export{default as Login} from './loginPage/Login'
export{default as Products} from './cosmeticsPage/Products'
export{default as ProductPage} from './productPage/ProductPage'